CREATE TABLE `sap_maintenance_order_confirmation_header_data`
(
  `MaintOrderConf`                  varchar(10) NOT NULL,
  `MaintOrderConfCntrValue`         varchar(8) NOT NULL,
  `MaintenanceOrder`                varchar(12) DEFAULT NULL,
  `MaintenanceOrderOperation`       varchar(4) DEFAULT NULL,
  `MaintenanceOrderSubOperation`    varchar(4) DEFAULT NULL,
  `PersonnelNumber`                 varchar(8) DEFAULT NULL,
  `ActualWorkQuantity`              varchar(9) DEFAULT NULL,
  `ActualWorkQuantityUnit`          varchar(3) DEFAULT NULL,
  `ActualDuration`                  varchar(7) DEFAULT NULL,
  `ActualDurationUnit`              varchar(3) DEFAULT NULL,
  `OperationConfirmedStartDate`     varchar(80) DEFAULT NULL,
  `OperationConfirmedStartTime`     varchar(80) DEFAULT NULL,
  `OperationConfirmedEndDate`       varchar(80) DEFAULT NULL,
  `OperationConfirmedEndTime`       varchar(80) DEFAULT NULL,
  `IsFinalConfirmation`             tinyint(1) DEFAULT NULL,
  `NoFurtherWorkQuantityIsExpd`     tinyint(1) DEFAULT NULL,
  `RemainingWorkQuantity`           varchar(9) DEFAULT NULL,
  `RemainingWorkQuantityUnit`       varchar(3) DEFAULT NULL,
  `PostingDate`                     varchar(80) DEFAULT NULL,
  `ActivityType`                    varchar(6) DEFAULT NULL,
  `OpenReservationsIsCleared`       tinyint(1) DEFAULT NULL,
  `ConfirmationText`                varchar(40) DEFAULT NULL,
  `VarianceReasonCode`              varchar(4) DEFAULT NULL,
  `CapacityInternalID`              varchar(8) DEFAULT NULL,
  `NmbrOfMaintTechnicianCapSplits`  int(8) DEFAULT NULL,
  `MaterialDocument`                varchar(10) DEFAULT NULL,
  `AccountingIndicatorCode`         varchar(2) DEFAULT NULL,
  `ActyConfFcstdEndDate`            varchar(80) DEFAULT NULL,
  `ActyConfFcstdEndTime`            varchar(80) DEFAULT NULL,
    PRIMARY KEY (`MaintOrderConf`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
